### ISSUE TITLE
Installation and Running Problem

### ISSUE THREAD

**Issue by Huzaifa1818** [pepiuox/PHP-GrapesJS#31]
I'm trying to Install this script on localhost, but it's not working. On the first page, Images are not loading properly and links are not working.

**Comment by dezigns333** [comment]
I am getting the same issue. 
I removed the :130 from localhost because it is not applied to many of the folders. 
Disabling the installer links 'installer.php' is a hassle when you have to reinstall numerous times to debug the problem. 
The PIN feature does not work at all. It needs to be fixed or used for emergency, or optional, not on every login. It defeats the point of a password. I was accidently able to log in once. But I was unable to recreate the error to log in again. My point is, I have only been able to log in once after 10 installations. 
PHPMailer doesn't work so verification doesn't.

**Comment by pepiuox** [comment]
Hi, the files were updated, thanks for reporting bugs.
Now I fix phpmailer errors.
PePiuox
