### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by toanle91** [pepiuox/PHP-GrapesJS#34]
Hello,
Thanks for share project, It is very good for starter as me.
I have some question bellow, please give favor to help.

1. I see missing folder images on assets, so can you update?
2. I need make update for component or sections dymamic content. Example i have posts and when drage section blog i need dynamic load latest my post so can you help me give some idea or document?

Thanks!

**Comment by pepiuox** [comment]
Hello, 
What you can do is in the case of a blog, create the table you need in the database, and then an editor, then create as a component and template, and this component would be good to develop it in vuejs so that when it is drags can show you the content, and that depends on how you want to view it.

If you have any idea concept, maybe I can add it in the project.

BEst regards.

**Comment by toanle91** [comment]
Yes thanks for reply.
I think i will use one shortcode maybe like that
`[latest_blog]`
And will use php function replace that by latest post before render page.
Thanks!
