### ISSUE TITLE
No instruction for installation. 

### ISSUE THREAD

**Issue by d3cline** [pepiuox/PHP-GrapesJS#5]
How does one go about installing this package on a php shared host?

**Comment by d3cline** [comment]
Ah I see, you are using `.htaccess` to do most of the routing for this application. I would suggest not doing this as it makes the app only compatible with Apache. I am not a good enough PHP developer to rewrite this myself, so I am likely going to move on from your project. 

If you want it to gain traction, I suggest an installation instruction, and not using .htaccess or relying on the server deployment for any kind of routing or data.

**Comment by pepiuox** [comment]
> 
> 
> Ah I see, you are using `.htaccess` to do most of the routing for this application. I would suggest not doing this as it makes the app only compatible with Apache. I am not a good enough PHP developer to rewrite this myself, so I am likely going to move on from your project.
> 
> If you want it to gain traction, I suggest an installation instruction, and not using .htaccess or relying on the server deployment for any kind of routing or data.

Hello, 
 .htaccess it is necessary for the server to perform tasks like these, the problem with servers like nginx or apache is that these things you must configure and then make your router and this works, then I will be doing a manual since I will be including a system of access to edit.

Thanks for your comment.
